// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPpBemjBuOhGUEO7CtUUlI8X_O2T8VHTU',
    appId: '1:998649842412:web:6308d30b25690078e433c9',
    messagingSenderId: '998649842412',
    projectId: 'home-3a2b2',
    authDomain: 'home-3a2b2.firebaseapp.com',
    storageBucket: 'home-3a2b2.firebasestorage.app',
    measurementId: 'G-DSYCTCLW62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMTwGnnnFjFLPeOvrIuZjPHC-P0iG3dP8',
    appId: '1:998649842412:android:e82464cc4563ed82e433c9',
    messagingSenderId: '998649842412',
    projectId: 'home-3a2b2',
    storageBucket: 'home-3a2b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVIJxTUCqxnvrvyjE_1s_bxB5qxGl14sg',
    appId: '1:998649842412:ios:8ad27abb442eb1f7e433c9',
    messagingSenderId: '998649842412',
    projectId: 'home-3a2b2',
    storageBucket: 'home-3a2b2.firebasestorage.app',
    iosBundleId: 'com.example.homeFunction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVIJxTUCqxnvrvyjE_1s_bxB5qxGl14sg',
    appId: '1:998649842412:ios:8ad27abb442eb1f7e433c9',
    messagingSenderId: '998649842412',
    projectId: 'home-3a2b2',
    storageBucket: 'home-3a2b2.firebasestorage.app',
    iosBundleId: 'com.example.homeFunction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPpBemjBuOhGUEO7CtUUlI8X_O2T8VHTU',
    appId: '1:998649842412:web:4875fc96c3b1f32be433c9',
    messagingSenderId: '998649842412',
    projectId: 'home-3a2b2',
    authDomain: 'home-3a2b2.firebaseapp.com',
    storageBucket: 'home-3a2b2.firebasestorage.app',
    measurementId: 'G-LNF0KR66MN',
  );

}